# Generated by Django 4.2.2 on 2023-07-30 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BrokerListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=1883)),
                ('protocol', models.CharField(default='mqtt', max_length=10)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='kit_web_ui.broker')),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MqttConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('topic_root', models.CharField(max_length=200)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_configs', to='kit_web_ui.brokerlistener')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
    ]
