# Generated by Django 4.2.2 on 2023-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_web_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerlistener',
            name='protocol',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('mqtts', 'MQTTS'), ('ws', 'Websocket'), ('wss', 'Websocket Secure')], default='mqtt', max_length=10),
        ),
    ]
