# Generated by Django 4.2.2 on 2024-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_web_ui', '0003_auditevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttconfig',
            options={'default_permissions': (), 'ordering': ['team_number', 'name']},
        ),
        migrations.AddField(
            model_name='mqttconfig',
            name='team_number',
            field=models.IntegerField(default=100),
        ),
    ]
