# Generated by Django 4.2.2 on 2024-07-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit_web_ui', '0004_alter_mqttconfig_options_mqttconfig_team_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subtopic', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('run_uuid', models.CharField(blank=True, default='', max_length=32)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='kit_web_ui.mqttconfig')),
            ],
            options={
                'ordering': ['-date'],
                'default_permissions': (),
            },
        ),
    ]
