name: Lint & build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build
        python -m pip install --no-deps .[dev]
    - name: Lint
      run: |
        make lint
    - name: Isort
      run: |
        make isort-check
    - name: Typecheck
      run: |
        make type
    - name: Build package
      run: |
        make build
    - name: Save built package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: |
          dist
